### ISSUE TITLE
Discussion of missing value treatment

### ISSUE THREAD

**Issue by rheuer83** [rrodriguezbarron/UML-Project#13]
How are we going to handle missing values?

Imputation? If yes, how?

**Comment by rrodriguezbarron** [comment]
I believe the best route is to replace with NA_real. This will work for most purposes. However, for things like SOM, the best way to handle them would be to choose the average or set them to the median value. There are problems with both approaches and both are used in the literature (Trier and Hillygus, 2009). If using the mean, we increase the skewness originally presented (in some bases by a lot, e.g. this week's ANES data went from 12000 to about 900 if you remove all rows with NAs). If we set the to the median, we will be inflating the non-committal moderates and that in itself is a problem because it has been known to affect the temporal stability of ideology as a construct (Wood & Oliver, 2012).  

Sources: 

- Treier, Shawn, and D. Sunshine Hillygus. 2009. “The Nature of Political Ideology in the Contemporary Electorate.” _Public Opinion Quarterly_ 73 (4): 679–703. https://doi.org/10.1093/poq/nfp067.
- Wood, Thomas, and Eric Oliver. 2012. “Toward a More Reliable Implementation of Ideology in Measures of Public Opinion.” _Public Opinion Quarterly_ 76 (4): 636–62. https://doi.org/10.1093/poq/nfs045.

**Comment by rrodriguezbarron** [comment]
Added in the Methods section of the Report.
