### ISSUE TITLE
Conclusion

### ISSUE THREAD

**Issue by sfergusond** [rrodriguezbarron/UML-Project#26]
Our results support the assumption that politically-themed media tend to have distinct consumer groups based on political ideology. Extending this hypothesis to the entertainment space had mixed results. TV shows with very few political themes, such as \emph{The Big Bang Theory}, had no separation in the ideologies of its viewers. Thus, sources of pure entertainment have a buffer against the cognitive biases that result in the polarized landscape of political media. However, sources of entertainment that contain political elements or have heavy thematic elements based on other facets of self-identification, such as race, may result in distinct ideological audiences. Viewers of Stephen Colbert, for example, skew liberal because he satirizes conservative media. Viewers of \emph{Empire} skew liberal, but do not overlap with the Colbert audience. This is likely because \emph{Empire} caters to an African-American audience.

**Comment by rrodriguezbarron** [comment]
Added and modified \emph{The Late Show with Stephen Colbert}

**Comment by rheuer83** [comment]
Subgroups of ANES respondents who reported consuming political as well as certain entertainment formats turned out to possess interesting ideological profiles. The intersection of Sean Hannity viewers and NCIS viewers, for example picked out almost exclusively ideological conservatives. These cross-domain combinations were comparable with respect to ideological composition to intersections of multiple purely political formats. What this means in substantive terms, however, is hard to determine without analyzing the respective media items in terms of content. The method we deployed in our study might nonetheless prove generative for subsequent research.

**Comment by rrodriguezbarron** [comment]
Added them.
